format_version: 10
pipelines:
  tools-prometheus:
    group: create
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-2ae7d73:
        git: https://github.com/devps23/multipleSubnets.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - test-stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          terraform-apply:
            timeout: 0
            tasks:
            - exec: { command: ansible-playbook,  arguments: [ "init" ], run_if: passed }
            - exec: { command: ansible-playbook,  arguments: [ "apply" ,"-auto_approve" ], run_if: passed }




